language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


before_script:
 - git clone https://github.com/xiongxliu/hexo-theme-next.git themes/next

script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "xiongxliu"
  - git config user.email "xiongx.liu@gmail.com"
  - git add -A
  - git commit -m "Update docs"
  - git push --force --quiet "https://${TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/xiongxliu/hexo-site.git